
name: Build_wheel

on:  
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_wheels:
    runs-on: ubuntu-latest
    container: dingodatabase/dingo-eureka:rocky9
 
    steps:
      - uses: actions/checkout@v4
      - name: Set Safe Dir
        run: git config --global --add safe.directory $PWD
      - name: Install default Python version
        run: |
          dnf install -y python3 python3-devel python3-venv
      - name: Download the submodule
        run: |
          git submodule sync --recursive
          git submodule update --init --recursive
      - name: Build wheels
        uses: pypa/cibuildwheel@v2.19.1
        env:
          CIBW_BUILD_FRONTEND: build

      - uses: actions/upload-artifact@v4
        with:
          name: sdk_whl
          path: ./wheelhouse/*.whl